import { useEffect, useMemo, useState } from "react";
import { Navigate, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { useQueryClient } from "@tanstack/react-query";
import { X, Volume2, Mic } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { enrichConcepts, isCloseEnough, speakSpanish, updateMemory, type ConceptWithMemory } from "@/lib/lingua";
import { useAuthStore } from "@/stores/authStore";
import { useLessonStore, type Exercise } from "@/stores/lessonStore";
import { useLesson } from "@/hooks/useLessons";

export default function Lesson() {
  const { id } = useParams();
  const [params] = useSearchParams();
  const mode = params.get("mode") === "flashcard" ? "flashcard" : "lesson";
  const { user, profile, refreshProfile } = useAuthStore();
  const store = useLessonStore();
  const navigate = useNavigate();
  const qc = useQueryClient();
  const [answered, setAnswered] = useState<null | boolean>(null);
  const [typed, setTyped] = useState("");
  const [flipped, setFlipped] = useState(false);
  const [correctStreak, setCorrectStreak] = useState(0);
  const [complete, setComplete] = useState(false);
  const query = useLesson(id, user?.id);
  useEffect(() => { store.reset(); setComplete(false); setCorrectStreak(0); }, [id, mode]);
  useEffect(() => { if (query.data?.concepts && profile && store.exercises.length === 0 && !complete) store.setLesson(makeExercises(query.data.concepts, mode), 99, mode); }, [query.data?.concepts, mode, complete]);
  const exercise = store.exercises[store.currentIndex];
  const options = useMemo(() => exercise ? makeOptions(exercise.concept, query.data?.concepts ?? []) : [], [exercise, query.data?.concepts]);
  if (!user) return <Navigate to="/login" />;
  if (query.isLoading || !exercise && !complete) return <main className="lif-page grid place-items-center"><div className="lif-skeleton h-48 w-full max-w-xl" /></main>;
  const finishAnswer = async (isCorrect: boolean) => {
    setAnswered(isCorrect);
    await updateMemory(exercise.concept, isCorrect, exercise.concept.memory, user.id);
    if (!isCorrect) { store.addWrong(exercise); }
    else { const next = correctStreak + 1; setCorrectStreak(next); if (next % 4 === 0) store.reinsertWrong(); }
    setTimeout(() => nextStep(), isCorrect ? 650 : 2000);
  };
  const nextStep = () => { setAnswered(null); setTyped(""); setFlipped(false); if (store.currentIndex + 1 >= store.exercises.length) completeSession(); else store.next(); };
  const completeSession = async () => { const correctCount = store.exercises.length - store.wrongQueue.length; const xp = mode === "flashcard" ? 5 + correctCount : 10 + correctCount * 2; const today = new Date().toISOString().slice(0,10); const last = profile?.last_streak_date; const yesterday = new Date(Date.now()-86400000).toISOString().slice(0,10); const streak = !last || last < yesterday ? 1 : last < today ? (profile?.streak_days ?? 0) + 1 : profile?.streak_days ?? 0; await supabase.from("user_profiles").update({ xp_total: (profile?.xp_total ?? 0)+xp, weekly_xp: (profile?.weekly_xp ?? 0)+xp, streak_days: streak, last_streak_date: today, last_practiced: new Date().toISOString() }).eq("id", user.id); await supabase.from("sessions").insert({ user_id: user.id, unit_id: Number(id), session_type: mode, completed: true, xp_earned: xp }); await refreshProfile(); setComplete(true); store.reset(); qc.invalidateQueries(); };
  if (complete) return <End title="⭐ You earned XP!" subtitle="Great work — your memory schedule has been updated." primary="Continue →" onPrimary={() => navigate("/home")} />;
  return <main className="min-h-screen bg-background p-4"><div className="mx-auto max-w-2xl"><header className="mb-8 flex items-center gap-4"><button onClick={() => confirm("Exit lesson?") && navigate(`/unit/${id}`)} className="rounded-2xl p-2 hover:bg-muted"><X /></button><div className="h-4 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all" style={{ width: `${(store.currentIndex / store.exercises.length) * 100}%` }} /></div><span className="font-black">⭐ {profile?.xp_total ?? 0} XP</span></header><section className="lif-card min-h-[460px] p-6 text-center animate-pop">{exercise.type === "introduce" && <Intro concept={exercise.concept} onNext={nextStep} />}{exercise.type === "choice" && <Choice concept={exercise.concept} options={options} answered={answered} onPick={finishAnswer} />}{exercise.type === "translation" && <Translation concept={exercise.concept} typed={typed} setTyped={setTyped} onSubmit={() => finishAnswer(isCloseEnough(typed, exercise.concept.surface_form))} />}{exercise.type === "flashcard" && <Flashcard concept={exercise.concept} flipped={flipped} setFlipped={setFlipped} onAnswer={finishAnswer} />}{exercise.type === "speaking" && <Speaking concept={exercise.concept} onAnswer={finishAnswer} />}</section></div></main>;
}
function makeExercises(concepts: ConceptWithMemory[], mode: "lesson" | "flashcard"): Exercise[] { if (mode === "flashcard") return concepts.slice(0, 12).map((c,i)=>({id:`f-${i}`, type:"flashcard", concept:c})); const news = concepts.filter(c => (c.memory?.attempts ?? 0) === 0).slice(0,3); const reviews = concepts.filter(c => (c.memory?.attempts ?? 0) > 0 && c.recall < .6).sort((a,b)=>((b.memory?.adaptive_weight??1)*(1-b.recall))-((a.memory?.adaptive_weight??1)*(1-a.recall))).slice(0,8); const base = [...news, ...reviews.length ? reviews : concepts].slice(0,10); return base.flatMap((c,i)=> (c.memory?.attempts ?? 0)===0 ? [{id:`i-${i}`, type:"introduce", concept:c},{id:`q-${i}`, type:i%3===0?"speaking":i%2?"translation":"choice", concept:c}] : [{id:`r-${i}`, type:i%3===0?"speaking":i%2?"translation":"choice", concept:c}]).slice(0,15) as Exercise[]; }
function makeOptions(c: ConceptWithMemory, all: ConceptWithMemory[]) { return [c.translation, ...all.filter(x=>x.concept_id!==c.concept_id).slice(0,3).map(x=>x.translation)].sort(()=>Math.random()-.5); }
function Intro({ concept, onNext }: { concept: ConceptWithMemory; onNext:()=>void }) { return <div className="grid gap-5 place-items-center"><span className="rounded-full bg-primary-soft px-4 py-2 font-black text-primary">✨ New Word!</span><h1 className="text-5xl font-black">{concept.surface_form}</h1><button onClick={()=>speakSpanish(concept.surface_form)} className="text-6xl transition hover:scale-110">{concept.emoji}<Volume2 className="mx-auto mt-2" /></button><p className="text-2xl font-bold">{concept.translation}</p>{concept.mnemonic && <p className="italic text-muted-foreground">{concept.mnemonic}</p>}<Button onClick={onNext}>Got it! →</Button></div>; }
function Choice({ concept, options, answered, onPick }: { concept: ConceptWithMemory; options:string[]; answered:boolean|null; onPick:(v:boolean)=>void }) { return <div className="grid gap-5"><h1 className="text-2xl font-black">What does {concept.surface_form} mean?</h1><div className="grid gap-3">{options.map(o=><Button key={o} variant={answered===null?"outline":o===concept.translation?"default":"outline"} onClick={()=>answered===null && onPick(o===concept.translation)}>{o}</Button>)}</div>{answered===false && <p className="rounded-2xl bg-destructive-soft p-4 font-black text-destructive">Correct answer: {concept.translation}</p>}</div>; }
function Translation({ concept, typed, setTyped, onSubmit }: { concept: ConceptWithMemory; typed:string; setTyped:(v:string)=>void; onSubmit:()=>void }) { return <div className="grid gap-5"><h1 className="text-2xl font-black">Translate: {concept.translation}</h1><input autoFocus className="lif-input text-center text-2xl font-bold" value={typed} onChange={e=>setTyped(e.target.value)} /><Button onClick={onSubmit}>Submit</Button></div>; }
function Flashcard({ concept, flipped, setFlipped, onAnswer }: { concept: ConceptWithMemory; flipped:boolean; setFlipped:(v:boolean)=>void; onAnswer:(v:boolean)=>void }) { return <div className="grid gap-5"><button onClick={()=>setFlipped(!flipped)} className="min-h-72 rounded-2xl bg-primary-soft p-8 transition hover:scale-[1.01]"><p className="text-6xl">{concept.emoji}</p><h1 className="mt-4 text-5xl font-black text-primary">{flipped ? concept.translation : concept.surface_form}</h1><p className="mt-4 font-semibold text-muted-foreground">{flipped ? concept.mnemonic : "Tap to flip"}</p></button>{flipped && <div className="grid grid-cols-2 gap-3"><Button variant="dangerSoft" onClick={()=>onAnswer(false)}>😅 Missed it</Button><Button onClick={()=>onAnswer(true)}>✅ Got it</Button></div>}</div>; }
function Speaking({ concept, onAnswer }: { concept: ConceptWithMemory; onAnswer:(v:boolean)=>void }) { const [transcript,setTranscript]=useState(""); const [recording,setRecording]=useState(false); const supported = typeof window !== "undefined" && ((window as any).SpeechRecognition || (window as any).webkitSpeechRecognition); const start=()=>{ if(!supported) return; const Rec=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition; const rec=new Rec(); rec.lang="es-ES"; rec.interimResults=true; rec.onresult=(e:any)=>setTranscript(e.results[0][0].transcript); rec.onend=()=>setRecording(false); setRecording(true); rec.start(); }; if(!supported) return <Translation concept={concept} typed={transcript} setTyped={setTranscript} onSubmit={()=>onAnswer(isCloseEnough(transcript, concept.surface_form))} />; return <div className="grid gap-5 place-items-center"><h1 className="text-5xl font-black">{concept.surface_form}</h1><button onClick={start} className={`grid h-24 w-24 place-items-center rounded-full bg-destructive text-destructive-foreground ${recording?"animate-pulseRed":""}`}><Mic /></button><div className="min-h-16 w-full rounded-2xl bg-muted p-4 font-bold text-muted-foreground">{transcript || "Speak Spanish..."}</div><Button onClick={()=>onAnswer(isCloseEnough(transcript, concept.surface_form))}>Check pronunciation</Button></div>; }
function End({ title, subtitle, primary, secondary, onPrimary, onSecondary }: { title:string; subtitle:string; primary:string; secondary?:string; onPrimary:()=>void; onSecondary?:()=>void }) { return <main className="grid min-h-screen place-items-center bg-background p-4"><section className="lif-card grid max-w-md gap-4 p-8 text-center animate-pop"><h1 className="text-4xl font-black text-primary">{title}</h1><p className="font-semibold text-muted-foreground">{subtitle}</p><Button onClick={onPrimary}>{primary}</Button>{secondary && <Button variant="outline" onClick={onSecondary}>{secondary}</Button>}</section></main>; }
