import { Bar, BarChart, ResponsiveContainer, XAxis, YAxis, Tooltip } from "recharts";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { PageTopBar, LoadingGrid, ErrorState } from "@/components/lingua/AppShell";
import { StrengthBar } from "@/components/lingua/StrengthBar";
import { enrichConcepts, unitStrength, type Concept, type Memory, type Unit } from "@/lib/lingua";
import { useAuthStore } from "@/stores/authStore";

export default function Profile() {
  const { user, profile, signOut } = useAuthStore();
  const query = useQuery({ queryKey: ["profile", user?.id], enabled: !!user, queryFn: async () => { const [units, concepts, memory, sessions] = await Promise.all([supabase.from("units").select("*"), supabase.from("concepts").select("*"), supabase.from("user_memory").select("*").eq("user_id", user!.id), supabase.from("sessions").select("*").eq("user_id", user!.id).order("created_at", { ascending:false }).limit(100)]); if (units.error || concepts.error || memory.error || sessions.error) throw new Error("load"); return { units: units.data as Unit[], concepts: concepts.data as Concept[], memories: memory.data as Memory[], sessions: sessions.data as any[] }; }});
  if (query.isLoading) return <main className="lif-page"><div className="lif-shell"><PageTopBar /><LoadingGrid /></div></main>;
  if (query.isError || !query.data) return <main className="lif-page"><div className="lif-shell"><ErrorState onRetry={() => query.refetch()} /></div></main>;
  const concepts = enrichConcepts(query.data.concepts, query.data.memories); const learned = query.data.memories.filter(m=>m.attempts>0).length; const mastered = query.data.memories.filter(m=>m.half_life_est>14).length;
  const strength = (ids:number[]) => ids.every(id => unitStrength(concepts.filter(c=>c.unit_id===id)) >= .75); const level = strength([1,2,3,4,5]) ? strength([6,7,8]) ? strength([9,10]) ? "B1" : "A2" : "A1" : "Starter"; const levelValue = level==="B1"?.75:level==="A2"?.5:level==="A1"?.25:.08;
  const chart = Array.from({length:7},(_,i)=>{ const d=new Date(Date.now()-(6-i)*86400000); const key=d.toISOString().slice(0,10); return { day: d.toLocaleDateString(undefined,{weekday:"short"}), xp: query.data.sessions.filter(s=>s.created_at?.slice(0,10)===key).reduce((a,s)=>a+(s.xp_earned??0),0) }; });
  const strongest = [...concepts].filter(c=>c.memory).sort((a,b)=>(b.memory?.half_life_est??0)-(a.memory?.half_life_est??0)).slice(0,3); const weakest = [...concepts].filter(c=>(c.memory?.attempts??0)>0).sort((a,b)=>a.recall-b.recall).slice(0,3);
  const initials = (profile?.display_name?.[0] ?? user?.email?.[0] ?? "L").toUpperCase();
  return <main className="lif-page"><div className="lif-shell max-w-5xl"><PageTopBar /><section className="lif-card mb-5 flex items-center gap-4 p-6"><div className="grid h-20 w-20 place-items-center rounded-2xl bg-primary text-3xl font-black text-primary-foreground">{initials}</div><div><h1 className="text-3xl font-black">{profile?.display_name ?? "Learner"}</h1><p className="font-semibold text-muted-foreground">{user?.email}</p></div></section><section className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="🔥 Day Streak" value={profile?.streak_days??0}/><Stat label="⚡ Total XP" value={profile?.xp_total??0}/><Stat label="📚 Words Learned" value={learned}/><Stat label="⭐ Words Mastered" value={mastered}/></section><section className="mb-5 grid gap-5 md:grid-cols-2"><div className="lif-card p-5"><h2 className="mb-3 text-xl font-black">CEFR Level Estimate: {level}</h2><StrengthBar value={levelValue}/><div className="mt-2 flex justify-between text-xs font-black text-muted-foreground"><span>A1</span><span>A2</span><span>B1</span><span>B2</span></div><p className="mt-4 rounded-2xl bg-accent-soft p-3 font-black">League: {profile?.league ?? "Bronze"}</p></div><div className="lif-card h-64 p-5"><h2 className="mb-3 text-xl font-black">Weekly XP</h2><ResponsiveContainer width="100%" height="80%"><BarChart data={chart}><XAxis dataKey="day"/><YAxis/><Tooltip/><Bar dataKey="xp" fill="hsl(var(--primary))" radius={[10,10,0,0]}/></BarChart></ResponsiveContainer></div></section><section className="mb-5 grid gap-5 md:grid-cols-2"><List title="Top 3 strongest words" rows={strongest}/><List title="Top 3 weakest words" rows={weakest}/></section><Button variant="outline" onClick={signOut}>Sign Out</Button></div></main>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="lif-stat"><p className="text-3xl font-black">{value}</p><p className="text-xs font-bold text-muted-foreground">{label}</p></div>}
function List({title,rows}:{title:string;rows:any[]}){return <div className="lif-card p-5"><h2 className="mb-3 text-xl font-black">{title}</h2><div className="grid gap-2">{rows.length?rows.map(r=><div key={r.concept_id} className="flex justify-between rounded-2xl bg-muted p-3 font-bold"><span>{r.emoji} {r.surface_form}</span><span>{Math.round(r.recall*100)}%</span></div>):<p className="font-semibold text-muted-foreground">No practice data yet.</p>}</div></div>}
