import { useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { PageTopBar, LoadingGrid, ErrorState } from "@/components/lingua/AppShell";
import { StrengthBar } from "@/components/lingua/StrengthBar";
import { VocabModal } from "@/components/lingua/VocabModal";
import { enrichConcepts, formatDays, type Concept, type ConceptWithMemory, type Memory, type Unit } from "@/lib/lingua";
import { useAuthStore } from "@/stores/authStore";

export default function Vocabulary() {
  const { user } = useAuthStore(); const [params] = useSearchParams();
  const [topic, setTopic] = useState(params.get("filter") === "forgotten" ? "Forgotten" : "All");
  const [search, setSearch] = useState(""); const [sort, setSort] = useState("due"); const [selected, setSelected] = useState<ConceptWithMemory | null>(null);
  const query = useQuery({ queryKey: ["vocab", user?.id], enabled: !!user, queryFn: async () => { const [units, concepts, memory] = await Promise.all([supabase.from("units").select("*"), supabase.from("concepts").select("*"), supabase.from("user_memory").select("*").eq("user_id", user!.id)]); if (units.error || concepts.error || memory.error) throw new Error("load"); return { units: units.data as Unit[], concepts: enrichConcepts(concepts.data as Concept[], memory.data as Memory[]) }; }});
  const filtered = useMemo(() => { let rows = query.data?.concepts ?? []; if (topic === "Forgotten") rows = rows.filter(c=>c.recall < .4 && (c.memory?.attempts??0)>0); else if (topic !== "All") rows = rows.filter(c=>c.topic===topic); if (search) rows = rows.filter(c => `${c.surface_form} ${c.translation}`.toLowerCase().includes(search.toLowerCase())); return [...rows].sort((a,b)=> sort === "weak" ? a.recall-b.recall : sort === "recent" ? +new Date(b.memory?.last_practiced??0)-+new Date(a.memory?.last_practiced??0) : sort === "az" ? a.surface_form.localeCompare(b.surface_form) : a.daysUntilReview-b.daysUntilReview); }, [query.data, topic, search, sort]);
  if (query.isLoading) return <main className="lif-page"><div className="lif-shell"><PageTopBar /><LoadingGrid /></div></main>;
  if (query.isError || !query.data) return <main className="lif-page"><div className="lif-shell"><ErrorState onRetry={() => query.refetch()} /></div></main>;
  const learned = query.data.concepts.filter(c => (c.memory?.attempts ?? 0) > 0);
  return <main className="lif-page"><div className="lif-shell"><PageTopBar /><section className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Total Learned" value={learned.length} /><Stat label="Due for Review" value={learned.filter(c=>c.recall<.6).length} /><Stat label="Strong" value={learned.filter(c=>c.recall>=.9).length} /><Stat label="Forgotten" value={learned.filter(c=>c.recall<.4).length} /></section><div className="mb-5 grid gap-3 md:grid-cols-[1fr_220px]"><input className="lif-input" placeholder="Search Spanish or English" value={search} onChange={e=>setSearch(e.target.value)} /><select className="lif-input" value={sort} onChange={e=>setSort(e.target.value)}><option value="due">Due soonest</option><option value="weak">Weakest first</option><option value="recent">Recently learned</option><option value="az">A–Z</option></select></div><div className="mb-5 flex gap-2 overflow-x-auto pb-2">{["All","Forgotten",...query.data.units.map(u=>u.topic)].map(t=><button key={t} onClick={()=>setTopic(t)} className={`shrink-0 rounded-2xl px-4 py-2 text-sm font-black ${topic===t?"bg-primary text-primary-foreground":"bg-muted text-muted-foreground"}`}>{t}</button>)}</div><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(c => <WordCard key={c.concept_id} c={c} onClick={() => setSelected(c)} />)}</section><VocabModal concept={selected} open={!!selected} onOpenChange={(o)=>!o&&setSelected(null)} /></div></main>;
}
function Stat({ label, value }: { label:string; value:number }) { return <div className="lif-stat"><p className="text-3xl font-black">{value}</p><p className="text-xs font-bold text-muted-foreground">{label}</p></div>; }
function WordCard({ c, onClick }: { c: ConceptWithMemory; onClick:()=>void }) { const attempts=c.memory?.attempts??0; const pct=Math.round((attempts?c.recall:0)*100); const color=c.recall>=.8?"text-primary":c.recall>=.5?"text-warning":"text-destructive"; return <button onClick={onClick} className={`lif-card p-4 text-left transition hover:-translate-y-1 hover:shadow-lg ${attempts===0?"opacity-75":""}`}><div className="mb-3 flex justify-between gap-2"><div><h3 className="text-xl font-black">{c.emoji} {c.surface_form}</h3><p className="font-semibold text-muted-foreground">{c.translation}</p></div><span className="rounded-full bg-muted px-2 py-1 text-xs font-black capitalize">{attempts===0?"⬜ New":c.status}</span></div><div className="my-3"><StrengthBar value={attempts?c.recall:0} /></div><p className="font-bold">Memory: <span className={color}>{pct}%</span></p><p className="text-sm font-semibold text-muted-foreground">Half-life: {(c.memory?.half_life_est??1).toFixed(1)} days</p><p className="text-sm font-semibold text-muted-foreground">Next review: {formatDays(c.daysUntilReview)}</p><p className="mt-3 border-t pt-3 text-sm font-bold text-muted-foreground">Seen: {attempts}× ✓{c.memory?.correct??0} ✗{c.memory?.incorrect??0} · {c.part_of_speech}</p>{attempts===0 && <p className="mt-2 text-sm font-black text-muted-foreground">⬜ Not yet learned · {'★'.repeat(c.difficulty_level)}</p>}</button>; }
