-- Seed LinguaFlow units and concepts from public/spanish_concepts.json
-- Generated from the concepts array; entries with _comment are skipped.

INSERT INTO public.units (id, topic, cefr_level, description, order_index, emoji) VALUES
  (1, 'Core', 'A1', 'Pronouns, articles, core verbs, conjunctions', 1, '🔤'),
  (2, 'Greetings', 'A1', 'Basic social phrases and politeness', 2, '👋'),
  (3, 'Numbers', 'A1', 'Cardinal and ordinal numbers', 3, '🔢'),
  (4, 'Food', 'A1', 'Common foods, drinks, eating verbs', 4, '🍎'),
  (5, 'Family', 'A1', 'Family relationships and household', 5, '👨‍👩‍👧'),
  (6, 'Time', 'A2', 'Days, hours, temporal expressions', 6, '🕐'),
  (7, 'Travel', 'A2', 'Transport, directions, places', 7, '✈️'),
  (8, 'Shopping', 'A2', 'Prices, transactions, shops', 8, '🛍️'),
  (9, 'Work', 'B1', 'Office, jobs, professional interaction', 9, '💼'),
  (10, 'Emergency', 'A2', 'Safety, medical, urgent phrases', 10, '🚨')
ON CONFLICT (id) DO UPDATE SET
  topic = EXCLUDED.topic,
  cefr_level = EXCLUDED.cefr_level,
  description = EXCLUDED.description,
  order_index = EXCLUDED.order_index,
  emoji = COALESCE(public.units.emoji, EXCLUDED.emoji);

INSERT INTO public.concepts (
  concept_id, surface_form, translation, topic, part_of_speech, difficulty_level,
  frequency, base_weight, skill_affinity, unit_id, mnemonic, gender, emoji
) VALUES
  ('es:yo', 'yo', 'I (first person singular)', 'Core', 'pronoun', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:tu', 'tú', 'you (informal singular)', 'Core', 'pronoun', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:el_pron', 'él', 'he', 'Core', 'pronoun', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:ella', 'ella', 'she', 'Core', 'pronoun', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:nosotros', 'nosotros', 'we (masculine/mixed)', 'Core', 'pronoun', 1, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:ellos', 'ellos', 'they (masculine/mixed)', 'Core', 'pronoun', 1, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:ser', 'ser', 'to be (permanent)', 'Core', 'verb', 1, 'high', 4.4, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:estar', 'estar', 'to be (temporary)', 'Core', 'verb', 1, 'high', 4.4, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:tener', 'tener', 'to have', 'Core', 'verb', 1, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:hacer', 'hacer', 'to do / to make', 'Core', 'verb', 1, 'high', 4.4, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:ir', 'ir', 'to go', 'Core', 'verb', 1, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:venir', 'venir', 'to come', 'Core', 'verb', 1, 'high', 4.4, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:querer', 'querer', 'to want', 'Core', 'verb', 1, 'high', 4.4, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:poder', 'poder', 'to be able to / can', 'Core', 'verb', 1, 'high', 4.4, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:hablar', 'hablar', 'to speak', 'Core', 'verb', 1, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:comer', 'comer', 'to eat', 'Core', 'verb', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:beber', 'beber', 'to drink', 'Core', 'verb', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:el_art', 'el', 'the (masculine singular)', 'Core', 'article', 1, 'high', 3.8, ARRAY['reading_core', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:la_art', 'la', 'the (feminine singular)', 'Core', 'article', 1, 'high', 3.8, ARRAY['reading_core', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:un', 'un', 'a / an (masculine)', 'Core', 'article', 1, 'high', 3.8, ARRAY['reading_core', 'listening_friendly']::text[], 1, NULL, NULL, NULL),
  ('es:hola', 'hola', 'hello', 'Greetings', 'interjection', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:adios', 'adiós', 'goodbye', 'Greetings', 'interjection', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:buenos_dias', 'buenos días', 'good morning', 'Greetings', 'phrase', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:buenas_tardes', 'buenas tardes', 'good afternoon', 'Greetings', 'phrase', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:buenas_noches', 'buenas noches', 'good night', 'Greetings', 'phrase', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:por_favor', 'por favor', 'please', 'Greetings', 'phrase', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:gracias', 'gracias', 'thank you', 'Greetings', 'interjection', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:de_nada', 'de nada', 'you''re welcome', 'Greetings', 'phrase', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:perdon', 'perdón', 'sorry / excuse me', 'Greetings', 'interjection', 1, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:salud', 'salud', 'bless you / health', 'Greetings', 'interjection', 1, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:como_estas', '¿cómo estás?', 'how are you?', 'Greetings', 'phrase', 1, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:bien', 'bien', 'well / good', 'Greetings', 'adverb', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:mal', 'mal', 'bad / poorly', 'Greetings', 'adverb', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:mas_o_menos', 'más o menos', 'more or less', 'Greetings', 'phrase', 1, 'medium', 2.9, ARRAY['speaking_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:mucho_gusto', 'mucho gusto', 'nice to meet you', 'Greetings', 'phrase', 1, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:hasta_luego', 'hasta luego', 'see you later', 'Greetings', 'phrase', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:bienvenido', 'bienvenido', 'welcome', 'Greetings', 'interjection', 1, 'medium', 2.9, ARRAY['speaking_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:que_tal', '¿qué tal?', 'what''s up?', 'Greetings', 'phrase', 1, 'medium', 2.9, ARRAY['speaking_friendly', 'listening_friendly']::text[], 2, NULL, NULL, NULL),
  ('es:uno', 'uno', 'one', 'Numbers', 'number', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:dos', 'dos', 'two', 'Numbers', 'number', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:tres', 'tres', 'three', 'Numbers', 'number', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:cuatro', 'cuatro', 'four', 'Numbers', 'number', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:cinco', 'cinco', 'five', 'Numbers', 'number', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:seis', 'seis', 'six', 'Numbers', 'number', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:siete', 'siete', 'seven', 'Numbers', 'number', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:ocho', 'ocho', 'eight', 'Numbers', 'number', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:nueve', 'nueve', 'nine', 'Numbers', 'number', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:diez', 'diez', 'ten', 'Numbers', 'number', 1, 'high', 3.8, ARRAY['speaking_friendly', 'listening_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:veinte', 'veinte', 'twenty', 'Numbers', 'number', 1, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:cien', 'cien', 'one hundred', 'Numbers', 'number', 1, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:mil', 'mil', 'one thousand', 'Numbers', 'number', 1, 'medium', 2.9, ARRAY['speaking_friendly']::text[], 3, NULL, NULL, NULL),
  ('es:primero', 'primero', 'first', 'Numbers', 'adjective', 1, 'medium', 2.9, ARRAY['reading_core']::text[], 3, NULL, NULL, NULL),
  ('es:segundo', 'segundo', 'second', 'Numbers', 'adjective', 1, 'medium', 2.9, ARRAY['reading_core']::text[], 3, NULL, NULL, NULL),
  ('es:manzana', 'manzana', 'apple', 'Food', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:pan', 'pan', 'bread', 'Food', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:agua', 'agua', 'water', 'Food', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:leche', 'leche', 'milk', 'Food', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:cafe', 'café', 'coffee', 'Food', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:te', 'té', 'tea', 'Food', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:arroz', 'arroz', 'rice', 'Food', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:pollo', 'pollo', 'chicken', 'Food', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:carne', 'carne', 'meat', 'Food', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:pescado', 'pescado', 'fish', 'Food', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:fruta', 'fruta', 'fruit', 'Food', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:verdura', 'verdura', 'vegetable', 'Food', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:hambre', 'hambre', 'hunger', 'Food', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly']::text[], 4, NULL, NULL, NULL),
  ('es:sed', 'sed', 'thirst', 'Food', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly']::text[], 4, NULL, NULL, NULL),
  ('es:desayuno', 'desayuno', 'breakfast', 'Food', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:almuerzo', 'almuerzo', 'lunch', 'Food', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:cena', 'cena', 'dinner', 'Food', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:restaurante', 'restaurante', 'restaurant', 'Food', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 4, NULL, NULL, NULL),
  ('es:cuenta', 'cuenta', 'bill (check)', 'Food', 'noun', 1, 'high', 4.4, ARRAY['listening_friendly']::text[], 4, NULL, NULL, NULL),
  ('es:cuchara', 'cuchara', 'spoon', 'Food', 'noun', 1, 'medium', 2.7, ARRAY['listening_friendly']::text[], 4, NULL, NULL, NULL),
  ('es:madre', 'madre', 'mother', 'Family', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:padre', 'padre', 'father', 'Family', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:hermano', 'hermano', 'brother', 'Family', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:hermana', 'hermana', 'sister', 'Family', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:hijo', 'hijo', 'son', 'Family', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:hija', 'hija', 'daughter', 'Family', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:abuela', 'abuela', 'grandmother', 'Family', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:abuelo', 'abuelo', 'grandfather', 'Family', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:familia', 'familia', 'family', 'Family', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:esposo', 'esposo', 'husband', 'Family', 'noun', 1, 'medium', 2.9, ARRAY['listening_friendly']::text[], 5, NULL, NULL, NULL),
  ('es:esposa', 'esposa', 'wife', 'Family', 'noun', 1, 'medium', 2.9, ARRAY['listening_friendly']::text[], 5, NULL, NULL, NULL),
  ('es:amigo', 'amigo', 'friend (male)', 'Family', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:amiga', 'amiga', 'friend (female)', 'Family', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:bebe', 'bebé', 'baby', 'Family', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:persona', 'persona', 'person', 'Family', 'noun', 1, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:nino', 'niño', 'child / boy', 'Family', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:nina', 'niña', 'child / girl', 'Family', 'noun', 1, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 5, NULL, NULL, NULL),
  ('es:vivo_con', 'vivo con', 'I live with', 'Family', 'phrase', 1, 'medium', 3.2, ARRAY['speaking_friendly']::text[], 5, NULL, NULL, NULL),
  ('es:hoy', 'hoy', 'today', 'Time', 'adverb', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:manana', 'mañana', 'tomorrow', 'Time', 'adverb', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:ayer', 'ayer', 'yesterday', 'Time', 'adverb', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:ahora', 'ahora', 'now', 'Time', 'adverb', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:despues', 'después', 'after / later', 'Time', 'adverb', 2, 'high', 4.1, ARRAY['listening_friendly']::text[], 6, NULL, NULL, NULL),
  ('es:antes', 'antes', 'before', 'Time', 'adverb', 2, 'high', 4.1, ARRAY['listening_friendly']::text[], 6, NULL, NULL, NULL),
  ('es:lunes', 'lunes', 'Monday', 'Time', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:martes', 'martes', 'Tuesday', 'Time', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:miercoles', 'miércoles', 'Wednesday', 'Time', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:jueves', 'jueves', 'Thursday', 'Time', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:viernes', 'viernes', 'Friday', 'Time', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:sabado', 'sábado', 'Saturday', 'Time', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:domingo', 'domingo', 'Sunday', 'Time', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:hora', 'hora', 'hour', 'Time', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:minuto', 'minuto', 'minute', 'Time', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:tiempo', 'tiempo', 'time / weather', 'Time', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:semana', 'semana', 'week', 'Time', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:mes', 'mes', 'month', 'Time', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:ano', 'año', 'year', 'Time', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:calendario', 'calendario', 'calendar', 'Time', 'noun', 2, 'medium', 3.2, ARRAY['reading_core']::text[], 6, NULL, NULL, NULL),
  ('es:aeropuerto', 'aeropuerto', 'airport', 'Travel', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly', 'reading_core']::text[], 7, NULL, NULL, NULL),
  ('es:avion', 'avión', 'airplane', 'Travel', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 7, NULL, NULL, NULL),
  ('es:tren', 'tren', 'train', 'Travel', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 7, NULL, NULL, NULL),
  ('es:hotel', 'hotel', 'hotel', 'Travel', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 7, NULL, NULL, NULL),
  ('es:pasaporte', 'pasaporte', 'passport', 'Travel', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly', 'reading_core']::text[], 7, NULL, NULL, NULL),
  ('es:mapa', 'mapa', 'map', 'Travel', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 7, NULL, NULL, NULL),
  ('es:calle', 'calle', 'street', 'Travel', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 7, NULL, NULL, NULL),
  ('es:direccion', 'dirección', 'direction / address', 'Travel', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly', 'reading_core']::text[], 7, NULL, NULL, NULL),
  ('es:izquierda', 'izquierda', 'left', 'Travel', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly']::text[], 7, NULL, NULL, NULL),
  ('es:derecha', 'derecha', 'right', 'Travel', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly']::text[], 7, NULL, NULL, NULL),
  ('es:recto', 'recto', 'straight ahead', 'Travel', 'adverb', 2, 'high', 4.1, ARRAY['listening_friendly']::text[], 7, NULL, NULL, NULL),
  ('es:cerca', 'cerca', 'near', 'Travel', 'adverb', 2, 'high', 4.1, ARRAY['listening_friendly']::text[], 7, NULL, NULL, NULL),
  ('es:lejos', 'lejos', 'far', 'Travel', 'adverb', 2, 'high', 4.1, ARRAY['listening_friendly']::text[], 7, NULL, NULL, NULL),
  ('es:estacion', 'estación', 'station', 'Travel', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly', 'reading_core']::text[], 7, NULL, NULL, NULL),
  ('es:boleto', 'boleto', 'ticket', 'Travel', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 7, NULL, NULL, NULL),
  ('es:equipaje', 'equipaje', 'luggage', 'Travel', 'noun', 2, 'medium', 3.2, ARRAY['listening_friendly']::text[], 7, NULL, NULL, NULL),
  ('es:aduanas', 'aduanas', 'customs', 'Travel', 'noun', 2, 'medium', 3.5, ARRAY['listening_friendly']::text[], 7, NULL, NULL, NULL),
  ('es:reservacion', 'reservación', 'reservation', 'Travel', 'noun', 2, 'medium', 3.2, ARRAY['reading_core']::text[], 7, NULL, NULL, NULL),
  ('es:playa', 'playa', 'beach', 'Travel', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 7, NULL, NULL, NULL),
  ('es:precio', 'precio', 'price', 'Shopping', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 8, NULL, NULL, NULL),
  ('es:comprar', 'comprar', 'to buy', 'Shopping', 'verb', 2, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 8, NULL, NULL, NULL),
  ('es:vender', 'vender', 'to sell', 'Shopping', 'verb', 2, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 8, NULL, NULL, NULL),
  ('es:pagar', 'pagar', 'to pay', 'Shopping', 'verb', 2, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 8, NULL, NULL, NULL),
  ('es:tienda', 'tienda', 'store / shop', 'Shopping', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 8, NULL, NULL, NULL),
  ('es:mercado', 'mercado', 'market', 'Shopping', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 8, NULL, NULL, NULL),
  ('es:dinero', 'dinero', 'money', 'Shopping', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 8, NULL, NULL, NULL),
  ('es:tarjeta', 'tarjeta', 'card', 'Shopping', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 8, NULL, NULL, NULL),
  ('es:efectivo', 'efectivo', 'cash', 'Shopping', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly']::text[], 8, NULL, NULL, NULL),
  ('es:caro', 'caro', 'expensive', 'Shopping', 'adjective', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 8, NULL, NULL, NULL),
  ('es:barato', 'barato', 'cheap', 'Shopping', 'adjective', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 8, NULL, NULL, NULL),
  ('es:gratis', 'gratis', 'free', 'Shopping', 'adjective', 2, 'high', 3.8, ARRAY['listening_friendly']::text[], 8, NULL, NULL, NULL),
  ('es:descuento', 'descuento', 'discount', 'Shopping', 'noun', 2, 'medium', 3.2, ARRAY['listening_friendly']::text[], 8, NULL, NULL, NULL),
  ('es:recibo', 'recibo', 'receipt', 'Shopping', 'noun', 2, 'medium', 3.2, ARRAY['reading_core']::text[], 8, NULL, NULL, NULL),
  ('es:cambio', 'cambio', 'change (money)', 'Shopping', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly']::text[], 8, NULL, NULL, NULL),
  ('es:oferta', 'oferta', 'offer / deal', 'Shopping', 'noun', 2, 'medium', 3.2, ARRAY['listening_friendly']::text[], 8, NULL, NULL, NULL),
  ('es:cantidad', 'cantidad', 'quantity / amount', 'Shopping', 'noun', 2, 'medium', 3.2, ARRAY['reading_core']::text[], 8, NULL, NULL, NULL),
  ('es:trabajo', 'trabajo', 'work / job', 'Work', 'noun', 3, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 9, NULL, NULL, NULL),
  ('es:oficina', 'oficina', 'office', 'Work', 'noun', 3, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 9, NULL, NULL, NULL),
  ('es:empresa', 'empresa', 'company', 'Work', 'noun', 3, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 9, NULL, NULL, NULL),
  ('es:jefe', 'jefe', 'boss', 'Work', 'noun', 3, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 9, NULL, NULL, NULL),
  ('es:reunion', 'reunión', 'meeting', 'Work', 'noun', 3, 'high', 4.4, ARRAY['listening_friendly', 'reading_core']::text[], 9, NULL, NULL, NULL),
  ('es:contrato', 'contrato', 'contract', 'Work', 'noun', 3, 'medium', 3.2, ARRAY['reading_core']::text[], 9, NULL, NULL, NULL),
  ('es:sueldo', 'sueldo', 'salary', 'Work', 'noun', 3, 'medium', 3.2, ARRAY['listening_friendly']::text[], 9, NULL, NULL, NULL),
  ('es:colega', 'colega', 'colleague', 'Work', 'noun', 3, 'medium', 3.2, ARRAY['listening_friendly']::text[], 9, NULL, NULL, NULL),
  ('es:profesion', 'profesión', 'profession', 'Work', 'noun', 3, 'medium', 3.2, ARRAY['reading_core']::text[], 9, NULL, NULL, NULL),
  ('es:doctor', 'doctor', 'doctor', 'Work', 'noun', 3, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 9, NULL, NULL, NULL),
  ('es:profesor', 'profesor', 'teacher', 'Work', 'noun', 3, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 9, NULL, NULL, NULL),
  ('es:estudiante', 'estudiante', 'student', 'Work', 'noun', 3, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 9, NULL, NULL, NULL),
  ('es:trabajar', 'trabajar', 'to work', 'Work', 'verb', 3, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 9, NULL, NULL, NULL),
  ('es:estudiar', 'estudiar', 'to study', 'Work', 'verb', 3, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 9, NULL, NULL, NULL),
  ('es:ensenar', 'enseñar', 'to teach', 'Work', 'verb', 3, 'medium', 3.2, ARRAY['speaking_friendly', 'listening_friendly']::text[], 9, NULL, NULL, NULL),
  ('es:aprender', 'aprender', 'to learn', 'Work', 'verb', 3, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 9, NULL, NULL, NULL),
  ('es:escribir', 'escribir', 'to write', 'Work', 'verb', 3, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 9, NULL, NULL, NULL),
  ('es:leer', 'leer', 'to read', 'Work', 'verb', 3, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 9, NULL, NULL, NULL),
  ('es:terminar', 'terminar', 'to finish', 'Work', 'verb', 3, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 9, NULL, NULL, NULL),
  ('es:empezar', 'empezar', 'to start / begin', 'Work', 'verb', 3, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 9, NULL, NULL, NULL),
  ('es:ayuda', 'ayuda', 'help', 'Emergency', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'speaking_friendly']::text[], 10, NULL, NULL, NULL),
  ('es:emergencia', 'emergencia', 'emergency', 'Emergency', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly', 'reading_core']::text[], 10, NULL, NULL, NULL),
  ('es:hospital', 'hospital', 'hospital', 'Emergency', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 10, NULL, NULL, NULL),
  ('es:policia', 'policía', 'police', 'Emergency', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly', 'reading_core']::text[], 10, NULL, NULL, NULL),
  ('es:medico', 'médico', 'doctor / physician', 'Emergency', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly', 'reading_core']::text[], 10, NULL, NULL, NULL),
  ('es:medicina', 'medicina', 'medicine', 'Emergency', 'noun', 2, 'high', 4.4, ARRAY['listening_friendly', 'reading_core']::text[], 10, NULL, NULL, NULL),
  ('es:peligro', 'peligro', 'danger', 'Emergency', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 10, NULL, NULL, NULL),
  ('es:perdido', 'perdido', 'lost', 'Emergency', 'adjective', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 10, NULL, NULL, NULL),
  ('es:accidente', 'accidente', 'accident', 'Emergency', 'noun', 2, 'medium', 3.2, ARRAY['reading_core']::text[], 10, NULL, NULL, NULL),
  ('es:llamar', 'llamar', 'to call', 'Emergency', 'verb', 2, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 10, NULL, NULL, NULL),
  ('es:necesitar', 'necesitar', 'to need', 'Emergency', 'verb', 2, 'high', 4.1, ARRAY['speaking_friendly', 'listening_friendly']::text[], 10, NULL, NULL, NULL),
  ('es:urgente', 'urgente', 'urgent', 'Emergency', 'adjective', 2, 'high', 4.4, ARRAY['listening_friendly', 'reading_core']::text[], 10, NULL, NULL, NULL),
  ('es:fuego', 'fuego', 'fire', 'Emergency', 'noun', 2, 'high', 3.8, ARRAY['listening_friendly', 'reading_core']::text[], 10, NULL, NULL, NULL),
  ('es:salida', 'salida', 'exit', 'Emergency', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 10, NULL, NULL, NULL),
  ('es:telefono', 'teléfono', 'telephone', 'Emergency', 'noun', 2, 'high', 4.1, ARRAY['listening_friendly', 'reading_core']::text[], 10, NULL, NULL, NULL),
  ('es:ambulancia', 'ambulancia', 'ambulance', 'Emergency', 'noun', 2, 'medium', 3.2, ARRAY['listening_friendly']::text[], 10, NULL, NULL, NULL)
ON CONFLICT (concept_id) DO NOTHING;
